# How to use python to interact with and process data

In [1]:
print("Welcome mohit")

Welcome mohit


In [5]:
list1=[1,2,4,12,42,32]
list2=[3,2,1,5,33,24]
cheap=map(min,list1,list2)
print(cheap)

In [6]:
for item in cheap:
    print(item)

1
2
1
5
33
24


In [8]:
# lamda 
# python's way of creating anoynomous functions, they have no name...
# they are of single line.

# only one expression is to be evaluated...

function_name = lambda a,b,c:a+b

In [10]:
function_name(1,2,3)

3

In [1]:
my_list=[]
for number in range(0,1000):
    if number % 2 ==0:
        my_list.append(number)
my_list;

In [2]:
my_list1=[number for number in range(0,1000) if number%2 != 0]
my_list1;

# these are list comprehension

# Numpy

In [4]:
import numpy as np

In [23]:
my_new_list=[1,2,3]
x=np.array(my_new_list)
x

array([1, 2, 3])

In [12]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [21]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
m.shape

(2, 3)

In [44]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
n=n.reshape(5,3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [51]:
o=np.linspace(0,4,9)
o


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [53]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [55]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [14]:
Z=[1,2,3]

In [16]:
np.diag(Z)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
p=np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
y

array([4, 5, 6])

In [24]:
x

array([1, 2, 3])

In [26]:
# dot product is direct

x.dot(y)

32

In [28]:
r=np.array([y,y**2])
r

array([[ 4,  5,  6],
       [16, 25, 36]])

In [30]:
r.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [32]:
np.shape(r)

(2, 3)

In [34]:
np.shape(r.T)

(3, 2)

In [35]:
r.dtype

dtype('int32')

In [37]:
r=r.astype('f')
r.dtype

dtype('float32')

In [48]:
a=np.array([1,2,3,4,5,6,11,21,1,43,2,11])
a

array([ 1,  2,  3,  4,  5,  6, 11, 21,  1, 43,  2, 11])

In [49]:
a.max()

43

In [50]:
a.min()

1

In [51]:
a.sum()

110

In [52]:
a.mean()

9.166666666666666

In [53]:
a.std()

11.617754611895633

In [54]:
a.argmax()

9

In [55]:
a.argmin()

0

In [57]:
arr=np.arange(13)**2
arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [58]:
arr[0], arr[1]

(0, 1)

In [61]:
arr[:3]

array([0, 1, 4], dtype=int32)

In [62]:
arr[-3:]

array([100, 121, 144], dtype=int32)

In [64]:
arr[-5::-3]

array([64, 25,  4], dtype=int32)

In [91]:
mat=np.arange(36)
mat.resize((6,6))
mat

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
mat[2,3]

15

In [83]:
mat[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [84]:
mat[-1,::2]

array([30, 32, 34])

In [87]:
mat[mat>20]



array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [92]:
mat[mat>20]=20
mat

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [94]:
mat2=mat[:3,:3]
mat2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [99]:
mat2[:]=0
mat2


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [100]:
mat

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [112]:
mat3=mat.copy()
mat3

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [114]:
mat3=mat3[3:6,3:6]
mat3


array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [115]:
mat

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [118]:
test=np.random.randint(1,10,(4,3))
test

array([[3, 1, 2],
       [9, 8, 9],
       [9, 7, 9],
       [7, 1, 6]])

In [120]:
for row in test:
    print(row)

[3 1 2]
[9 8 9]
[9 7 9]
[7 1 6]


In [122]:
for i in range(len(test)):
    print(test[i])

[3 1 2]
[9 8 9]
[9 7 9]
[7 1 6]


In [123]:
for i,row in enumerate(test):
    print('row',i,'is',row)
    

row 0 is [3 1 2]
row 1 is [9 8 9]
row 2 is [9 7 9]
row 3 is [7 1 6]


In [125]:
test2=test**2
test2

array([[ 9,  1,  4],
       [81, 64, 81],
       [81, 49, 81],
       [49,  1, 36]], dtype=int32)

In [127]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)
    

[3 1 2] + [9 1 4] = [12  2  6]
[9 8 9] + [81 64 81] = [90 72 90]
[9 7 9] + [81 49 81] = [90 56 90]
[7 1 6] + [49  1 36] = [56  2 42]


In [130]:
test2.resize(12)
test2

array([ 9,  1,  4, 81, 64, 81, 81, 49, 81, 49,  1, 36], dtype=int32)

In [132]:
test2[::3]

array([ 9, 81, 81, 49], dtype=int32)